### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by mirabilos** [webjars/datatables-plugins#17]
Hi,

please update to both reflect the name change to datatables.net (so people get dependencies right, cf. https://github.com/l-lin/angular-datatables/pull/766 for a case where it wasn’t) and update to version 1.10.12 of the plugins repository.

I didn’t find this artefact earlier when looking, so I created https://github.com/webjars/webjars/issues/1410 which you might wish to look at / use as basis.

**Comment by mirabilos** [comment]
(especially the `.DS_Store` exclusion)

**Comment by jamesward** [comment]
It looks like we'd also need to rename the artifact in the datatables WebJar: https://github.com/webjars/datatables

What should the name for the plugins be?

**Comment by mirabilos** [comment]
Hm, I just used “datatables.net-plugins” for everything, following e.g. “datatables.net-bs” which we also use

**Comment by jamesward** [comment]
It looks like the NPM and Bower names are still `datatables` for the main artifact: https://github.com/DataTables/DataTables

The plugins project doesn't seem to have an official name: https://github.com/DataTables/Plugins

So I'd rather not change this WebJar's name.  However I'll bump the version.

**Comment by mirabilos** [comment]
James Ward dixit:

>It looks like the NPM and Bower names are still `datatables` for the
>main artifact: https://github.com/DataTables/DataTables

The bower webjars, however, all use datatables.net{,-*}.
There is (was, once the new version will be released) only
one (angular-datatables) pulling in the without-.net name.

>The plugins project doesn't seem to have an official name:
>https://github.com/DataTables/Plugins

True.

>So I'd rather not change this WebJar's name.  However I'll bump the version.

Fair enough, but in this case please ensure it doesn’t pull
the datatables webjar automatically.

Thanks!

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by jamesward** [comment]
The Bower WebJars use the dependency definitions from the Bower repo.  Bower WebJars can only depend on Bower WebJars.  So changing the name of the Classic WebJars won't resolve an issue with a missing dependency.  If you are having trouble deploying Bower WebJars from http://webjars.org/bower then please file an issue at: http://github.com/webjars/webjars/issues
