### ISSUE TITLE
Cannot use this artefact

### ISSUE THREAD

**Issue by mirabilos** [webjars/datatables-plugins#18]
Thanks to this part of the POM…

    <dependencies>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>datatables</artifactId>
            <version>1.10.12</version>
        </dependency>
    </dependencies>

… I still cannot use the updated artefact (from https://github.com/webjars/datatables-plugins/issues/17 discussion) because we use the bower webjars for datatables.net itself (which is *also* a requirement, because *other* bower(-only) webjars depend on the bower webjars for datatables.net).

The maven error is “Could not find artifact org.webjars:datatables:jar:1.10.12”.

Shouldn’t it be possible to depend on org.webjars.bower:datatables.net from this webjar? If so, that would solve my problems.

**Comment by jamesward** [comment]
The `org.webjars:datatables:1.10.12` artifact definitely exists: https://repo1.maven.org/maven2/org/webjars/datatables/1.10.12/

We don't mix dependencies between Classic & Bower WebJars.
